---
- name: Install EPEL repository
  yum:
    name: epel-release
    state: latest
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "6") or
        (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7")

- name: Set EPEL repository as disabled by default
  replace:
    dest: "{{ item }}"
    regexp: "^enabled=1"
    replace: "enabled=0"
  with_items:
  - /etc/yum.repos.d/epel.repo
  - /etc/yum.repos.d/epel-testing.repo
